/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Chamod Sachin
 */
public class addVehicle extends javax.swing.JFrame {

    /**
     * Creates new form addVehicle
     */
    private static addVehicle a;
    private static dashboard d;
    
    public addVehicle() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        plate = new javax.swing.JTextField();
        type = new javax.swing.JComboBox();
        overide = new javax.swing.JCheckBox();
        addbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        dateTimePicker1 = new com.lavantech.gui.comp.DateTimePicker();

        jLabel13.setForeground(new java.awt.Color(201, 199, 199));
        jLabel13.setText("YYYY");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 74, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 199, 199));
        jLabel1.setText("Add Vehicle");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 199, 199));
        jLabel2.setText("Vehicle Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(201, 199, 199));
        jLabel3.setText("Vehicle Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        plate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        plate.setForeground(new java.awt.Color(51, 74, 95));
        jPanel1.add(plate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 250, -1));

        type.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        type.setForeground(new java.awt.Color(51, 74, 95));
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car", "Van", "Bicycle", "Threewheeler" }));
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 250, -1));

        overide.setBackground(new java.awt.Color(51, 74, 95));
        overide.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        overide.setForeground(new java.awt.Color(201, 199, 199));
        overide.setText("Override");
        overide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                overideMouseClicked(evt);
            }
        });
        overide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overideActionPerformed(evt);
            }
        });
        jPanel1.add(overide, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        addbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_add.png"))); // NOI18N
        addbtn.setBorder(null);
        addbtn.setBorderPainted(false);
        addbtn.setContentAreaFilled(false);
        addbtn.setFocusPainted(false);
        addbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_add (1).png"))); // NOI18N
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setContentAreaFilled(false);
        backbtn.setFocusPainted(false);
        backbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back (1).png"))); // NOI18N
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(201, 199, 199));
        jLabel6.setText("Arrival Date & Time");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, -1, -1));

        dateTimePicker1.setEnabled(false);
        dateTimePicker1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(dateTimePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 320, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void overideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overideActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overideActionPerformed

    private void overideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overideMouseClicked
        if(!overide.isSelected()){
            dateTimePicker1.setEnabled(false);
        }else{
            dateTimePicker1.setEnabled(true);
        }
    }//GEN-LAST:event_overideMouseClicked

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        d = new dashboard();
        d.setVisible(true);
        try {
                   d.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        Connection conn = null;
        PreparedStatement st = null;
        
        if(plate.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Vehicle Plate cannot be Empty");
        }
        else{
            try{
                conn = sql_connect.connectDB();
                String query = "INSERT INTO carDetails(vehicle_plate,vehicle_type,arrival_date_time) values(?,?,?)";
                st = conn.prepareStatement(query);

                st.setString(1, plate.getText());
                st.setInt(2, type.getSelectedIndex() + 1);

                java.util.Date d1 = dateTimePicker1.getCalendar().getTime();
                java.sql.Date d = new java.sql.Date(d1.getTime());
                st.setDate(3, d);
                st.execute();

                JOptionPane.showMessageDialog(null, "Vehicle Added!");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
            }finally{
                try{
                    conn.close();
                    st.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_addbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                a = new addVehicle();
                a.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton backbtn;
    private com.lavantech.gui.comp.DateTimePicker dateTimePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox overide;
    private javax.swing.JTextField plate;
    private javax.swing.JComboBox type;
    // End of variables declaration//GEN-END:variables
}
