/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Chamod Sachin
 */
public class deleteVehicle extends javax.swing.JFrame {

    /**
     * Creates new form deleteVehicle
     */
    private static dashboard d;
    
    public deleteVehicle() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public deleteVehicle(dashboard d) {
        initComponents();
        this.d = d;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refreshbtn = new javax.swing.JButton();
        backbtn4 = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 74, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 199, 199));
        jLabel1.setText("Delete Vehicle Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        refreshbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_refresh (1).png"))); // NOI18N
        refreshbtn.setBorder(null);
        refreshbtn.setBorderPainted(false);
        refreshbtn.setContentAreaFilled(false);
        refreshbtn.setFocusPainted(false);
        refreshbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_refresh.png"))); // NOI18N
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jPanel1.add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        backbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back.png"))); // NOI18N
        backbtn4.setBorder(null);
        backbtn4.setBorderPainted(false);
        backbtn4.setContentAreaFilled(false);
        backbtn4.setFocusPainted(false);
        backbtn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back (1).png"))); // NOI18N
        backbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 890, -1, -1));

        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_delete.png"))); // NOI18N
        deletebtn.setBorder(null);
        deletebtn.setBorderPainted(false);
        deletebtn.setContentAreaFilled(false);
        deletebtn.setFocusPainted(false);
        deletebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_delete (1).png"))); // NOI18N
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 890, -1, -1));

        vehicles.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        vehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehiclesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vehicles);
        Connection conn = null;
        PreparedStatement st = null;
        ResultSet rs = null;

        try{
            conn = sql_connect.connectDB();
            String q = "select vehicle_plate AS 'Vehicle Number', arrival_date_time AS 'Arrival Date and Time', departure_date_time AS 'Depature Date and Time', hours_parked As 'Hours Parked', payment AS 'Payment' from carDetails";
            st = conn.prepareStatement(q);
            rs = st.executeQuery();

            vehicles.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
        }finally{
            try{
                st.close();
                rs.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
            }
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1060, 750));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 970));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh(){
        Connection conn = null;
        PreparedStatement st = null;
        ResultSet rs = null;

        try{
            conn = sql_connect.connectDB();
            String q = "select vehicle_plate AS 'Vehicle Number', arrival_date_time AS 'Arrival Date and Time', departure_date_time AS 'Depature Date and Time', hours_parked As 'Hours Parked', payment AS 'Payment' from carDetails";
            st = conn.prepareStatement(q);
            rs = st.executeQuery();

            vehicles.setModel(DbUtils.resultSetToTableModel(rs));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
        }finally{
            try{
                st.close();
                rs.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
            }
        }
    }
    
    private void vehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclesMouseClicked
        
    }//GEN-LAST:event_vehiclesMouseClicked

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        refresh();
    }//GEN-LAST:event_refreshbtnActionPerformed

    private void backbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn4ActionPerformed
        d = new dashboard();
        d.setVisible(true);
        try {
                   d.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_backbtn4ActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int i = vehicles.getSelectedRow();
        TableModel model = vehicles.getModel();
        
        String query = "DELETE FROM carDetails WHERE vehicle_plate == '" +model.getValueAt(i, 0) + "'";
        
        Connection conn = null;
        PreparedStatement st = null;

        try{
            conn = sql_connect.connectDB();            
            st = conn.prepareStatement(query);
            st.execute();
            JOptionPane.showMessageDialog(null, "Selected Vehicle Details Deleted!");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
        }finally{
            try{
                st.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
            }
        }
        refresh();
    }//GEN-LAST:event_deletebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                deleteVehicle d = new deleteVehicle();
                d.setVisible(true);
                d.refresh();
                try {
                   d.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(deleteVehicle.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn4;
    private javax.swing.JButton deletebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JTable vehicles;
    // End of variables declaration//GEN-END:variables
}
