/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Chamod Sachin
 */
public class updateVehicle extends javax.swing.JFrame {

    /**
     * Creates new form updateVehicle
     */
    private static dashboard d;
    
    
    public updateVehicle() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public updateVehicle(dashboard d) {
        initComponents();
        this.d = d;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        type = new javax.swing.JComboBox();
        backbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicles = new javax.swing.JTable();
        updatebtn = new javax.swing.JButton();
        refreshbtn = new javax.swing.JButton();
        dateTimePicker1 = new com.lavantech.gui.comp.DateTimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 74, 95));
        jPanel1.setForeground(new java.awt.Color(51, 74, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(201, 199, 199));
        jLabel1.setText("Update Vehicle Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(201, 199, 199));
        jLabel2.setText("Vehicle Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 750, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(201, 199, 199));
        jLabel3.setText("Vehicle Type");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 800, -1, -1));

        number.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        number.setForeground(new java.awt.Color(51, 74, 95));
        number.setEnabled(false);
        jPanel1.add(number, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 750, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(201, 199, 199));
        jLabel4.setText("Arrival Date & Time");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 770, -1, -1));

        type.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        type.setForeground(new java.awt.Color(51, 74, 95));
        type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Car", "Van", "Bicycle", "Threewheeler" }));
        jPanel1.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 800, 250, -1));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setContentAreaFilled(false);
        backbtn.setFocusPainted(false);
        backbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back (1).png"))); // NOI18N
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 880, -1, -1));

        vehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehicle Plate", "Arrival Date/Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        vehicles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vehiclesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(vehicles);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 1060, 610));

        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_update.png"))); // NOI18N
        updatebtn.setBorder(null);
        updatebtn.setBorderPainted(false);
        updatebtn.setContentAreaFilled(false);
        updatebtn.setFocusPainted(false);
        updatebtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_update (1).png"))); // NOI18N
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        jPanel1.add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 880, -1, -1));

        refreshbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_refresh (1).png"))); // NOI18N
        refreshbtn.setBorder(null);
        refreshbtn.setBorderPainted(false);
        refreshbtn.setContentAreaFilled(false);
        refreshbtn.setFocusPainted(false);
        refreshbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_refresh.png"))); // NOI18N
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jPanel1.add(refreshbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));
        Connection conn = null;
        PreparedStatement st = null;
        ResultSet rs = null;

        try{
            conn = sql_connect.connectDB();
            DefaultTableModel model = (DefaultTableModel) vehicles.getModel();
            model.setRowCount(0);
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm a");
            String q = "select vehicle_plate AS 'Vehicle Number', arrival_date_time AS 'Arrival Date and Time', departure_date_time AS 'Depature Date and Time', hours_parked As 'Hours Parked', payment AS 'Payment' from carDetails";
            st = conn.prepareStatement(q);
            rs = st.executeQuery();

            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString("Vehicle Number"),dateFormat.format(rs.getDate("Arrival Date and Time"))});
            }

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
        }finally{
            try{
                st.close();
                rs.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
            }
        }

        dateTimePicker1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(dateTimePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 770, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 960));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refresh(){
        Connection conn = null;
        PreparedStatement st = null;
        ResultSet rs = null;

        try{
            conn = sql_connect.connectDB();
            DefaultTableModel model = (DefaultTableModel) vehicles.getModel();
            model.setRowCount(0);
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm a");
            String q = "select vehicle_plate AS 'Vehicle Number', arrival_date_time AS 'Arrival Date and Time', departure_date_time AS 'Depature Date and Time', hours_parked As 'Hours Parked', payment AS 'Payment' from carDetails";
            st = conn.prepareStatement(q);
            rs = st.executeQuery();

            while(rs.next())
				{
                                       model.addRow(new Object[]{rs.getString("Vehicle Number"),dateFormat.format(rs.getDate("Arrival Date and Time"))});
				}
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
        }finally{
            try{
                st.close();
                rs.close();
                conn.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
            }
        }
    }
    
    private void vehiclesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vehiclesMouseClicked
        int type = 0;
        int i = vehicles.getSelectedRow();
        TableModel model = vehicles.getModel();
        
        number.setText(model.getValueAt(i,0).toString());
        
    }//GEN-LAST:event_vehiclesMouseClicked

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        d = new dashboard();
        d.setVisible(true);
        try {
                   d.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        Connection conn = null;
        PreparedStatement st = null;
        
        if(number.getText().equals("") /*|| arrdate dep date*/){
        }
        
        try{
            conn = sql_connect.connectDB();
            String query = "UPDATE carDetails SET vehicle_type = ?,arrival_date_time = ? WHERE vehicle_plate = ?";
            st = conn.prepareStatement(query);
            
            st.setString(3, number.getText());
            st.setInt(1, type.getSelectedIndex() + 1);
            
            java.util.Date d1 = dateTimePicker1.getCalendar().getTime();
            java.sql.Date d = new java.sql.Date(d1.getTime());
            st.setDate(2, d);
         
            st.execute();
            
            JOptionPane.showMessageDialog(null, "Vehicle Updated!");
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
        }finally{
            try{
                conn.close();
                st.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Error! " + e.getMessage());
            }
        }
        refresh();
    }//GEN-LAST:event_updatebtnActionPerformed

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed
        refresh();
    }//GEN-LAST:event_refreshbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private com.lavantech.gui.comp.DateTimePicker dateTimePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField number;
    private javax.swing.JButton refreshbtn;
    private javax.swing.JComboBox type;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTable vehicles;
    // End of variables declaration//GEN-END:variables
}
