package UI;


import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import dashboard.authorize;
import dashboard.sql_connect;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import model.dbConnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bimsara Gimhan
 */
public class SignUpNew extends javax.swing.JFrame {
    
    Connection con = null;
    ResultSet rs = null;

    /**
     * Creates new form SignUpNew
     */
    public SignUpNew() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void signup(){
        try{
            
            if(txt_username.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Please Enter Username"); 
            }
            else if(txt_contactNumber.getText().length() > 10 || txt_contactNumber.getText().length() < 10){
                JOptionPane.showMessageDialog(null, "contact Number should be 10 digits"); 
            }
            else if(txt_nicNumber.getText().length() > 10 || txt_contactNumber.getText().length() < 10){
                JOptionPane.showMessageDialog(null, "NIC Number should be 10 digits"); 
            }
            else if(txt_contactNumber.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Please Enter Contact Number"); 
            }
            else if(txt_nicNumber.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Please Enter NIC Number"); 
            }
            else if(txt_answer.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Please Enter Answer"); 
            }
            else if(txt_password.getPassword().length == 0){
                 JOptionPane.showMessageDialog(null, "Please Enter a Password"); 
            }
            else if(txt_reenterP.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "Please Enter Confirm Password"); 
            }      
            else{
                con = sql_connect.connectDB();
                PreparedStatement stmt1 = con.prepareStatement("INSERT INTO users(username,contact_number,nic,sec_question,sec_answer, password,user_type) VALUES(?,?,?,?,?,?,?)");
                stmt1.setString(1, txt_username.getText());
                stmt1.setString(2, txt_contactNumber.getText());
                stmt1.setString(3, txt_nicNumber.getText());
                stmt1.setString(4, cmb_securityQ.getSelectedItem().toString());
                stmt1.setString(5, txt_answer.getText());
                stmt1.setString(6, txt_password.getText());
                stmt1.setString(7, "1");
                if(stmt1.executeUpdate() == 1)
                {
                    JOptionPane.showMessageDialog(null, "Registration Successfull");
                    LogInnew r = new LogInnew();
                    r.setVisible(true);
                    r.setSize(1100,960);
                    r.setLocationRelativeTo(null);

                    try {
                       r.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                    } catch (IOException ex) {
                        Logger.getLogger(LogInnew.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    this.dispose();
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "Registration failed");
                }
                con.close();
            }
  
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
       
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_contactNumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmb_securityQ = new javax.swing.JComboBox();
        txt_answer = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_nicNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_reenterP = new javax.swing.JPasswordField();
        backbtn3 = new javax.swing.JButton();
        backbtn4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(52, 74, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_username.setForeground(new java.awt.Color(51, 74, 95));
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, 310, 50));

        txt_contactNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_contactNumber.setForeground(new java.awt.Color(51, 74, 95));
        jPanel1.add(txt_contactNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 310, 50));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Contact Number :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("NIC Number :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, 23));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Security Question :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, -1, 30));

        cmb_securityQ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cmb_securityQ.setForeground(new java.awt.Color(51, 74, 95));
        cmb_securityQ.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Name of first pet", "Name of primary school", "Favourite book" }));
        jPanel1.add(cmb_securityQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 500, 310, 50));

        txt_answer.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_answer.setForeground(new java.awt.Color(51, 74, 95));
        jPanel1.add(txt_answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, 310, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Answer :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 580, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Password :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 640, -1, -1));

        txt_nicNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_nicNumber.setForeground(new java.awt.Color(51, 74, 95));
        jPanel1.add(txt_nicNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 310, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Re Enter Password :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 700, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourses/icons8-add-user-male-80.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, -1, -1));

        txt_password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 640, 310, 40));

        txt_reenterP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel1.add(txt_reenterP, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 700, 310, 40));

        backbtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_sign-up.png"))); // NOI18N
        backbtn3.setBorder(null);
        backbtn3.setBorderPainted(false);
        backbtn3.setContentAreaFilled(false);
        backbtn3.setFocusPainted(false);
        backbtn3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_sign-up (1).png"))); // NOI18N
        backbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn3ActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 830, -1, -1));

        backbtn4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back.png"))); // NOI18N
        backbtn4.setBorder(null);
        backbtn4.setBorderPainted(false);
        backbtn4.setContentAreaFilled(false);
        backbtn4.setFocusPainted(false);
        backbtn4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back (1).png"))); // NOI18N
        backbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn4ActionPerformed(evt);
            }
        });
        jPanel1.add(backbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 830, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn3ActionPerformed
            if(txt_password.getText().equals(txt_reenterP.getText()) == false)
            {
                JOptionPane.showMessageDialog(null, "Password and Confirm Passwords doesn't match!");
            }
            else{    
                signup();
               
            }
    }//GEN-LAST:event_backbtn3ActionPerformed

    private void backbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn4ActionPerformed
        LogInnew r = new LogInnew();
                r.setVisible(true);
                r.setSize(1100,960);
                r.setLocationRelativeTo(null);
                
                try {
                   r.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(LogInnew.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_backbtn4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUpNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUpNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUpNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUpNew.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUpNew s = new SignUpNew();
                s.setVisible(true);
                s.setSize(1100,960);
                
                try {
                   s.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(SignUpNew.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn3;
    private javax.swing.JButton backbtn4;
    private javax.swing.JComboBox cmb_securityQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_answer;
    private javax.swing.JTextField txt_contactNumber;
    private javax.swing.JTextField txt_nicNumber;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_reenterP;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
