/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Function;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Vageesha
 */
public class Individual_Record_View extends javax.swing.JFrame {

    /**
     * Creates new form Individual_Record_View
     */
    public Individual_Record_View() {
        initComponents();
    }
    
    public void getDetails(String VP){
        try{
             
         Connection conn = DatabaseConnection.connect();
         PreparedStatement DBOUTPUT6 = conn.prepareStatement("SELECT * FROM carDetails WHERE vehicle_plate = ?");
         DBOUTPUT6.setString(1, VP);
         ResultSet RS5 = DBOUTPUT6.executeQuery();
         
         if(RS5.next()){
             vehicle_plate_display.setText(RS5.getString("vehicle_plate"));
             vehicle_type_display.setText(Integer.toString(RS5.getInt("vehicle_type")));
             
             Date date = RS5.getDate("arrival_date_time");
             DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm a");  
             String SAD = dateFormat.format(date);
             vehicle_arrival_display.setText(SAD);
             
             if(RS5.getDate("departure_date_time") == null)
             {
                vehicle_departure_display.setText("");
                vehicle_hours_parked.setText("");
                vehicle_payment_display.setText("");
             }
             else
             {
                Date date2 = RS5.getDate("departure_date_time");  
                String SAD2 = dateFormat.format(date2);
                vehicle_departure_display.setText(SAD2);
                vehicle_hours_parked.setText(Integer.toString(RS5.getInt("hours_parked")));

                vehicle_payment_display.setText(Double.toString(RS5.getDouble("payment")));
             }
             
         }
         DBOUTPUT6.close();
         RS5.close();
         conn.close();
         }catch(Exception e){
             System.out.println(e);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vehicle_plate_display = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vehicle_type_display = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        vehicle_arrival_display = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        vehicle_departure_display = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        vehicle_payment_display = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        vehicle_hours_parked = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1100, 1100));

        jPanel2.setBackground(new java.awt.Color(51, 74, 95));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vehicle Information");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(250, 80, 520, 110);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Plate");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(220, 250, 260, 40);

        vehicle_plate_display.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_plate_display.setForeground(new java.awt.Color(219, 242, 255));
        vehicle_plate_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicle_plate_display.setText("123");
        jPanel2.add(vehicle_plate_display);
        vehicle_plate_display.setBounds(620, 250, 370, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(":-");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(560, 250, 40, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":-");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(560, 350, 40, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vehicle Type");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(220, 350, 260, 40);

        vehicle_type_display.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_type_display.setForeground(new java.awt.Color(219, 242, 255));
        vehicle_type_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicle_type_display.setText("123");
        jPanel2.add(vehicle_type_display);
        vehicle_type_display.setBounds(620, 350, 370, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Arrival Date/Time");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(220, 450, 260, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":-");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(560, 450, 40, 40);

        vehicle_arrival_display.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_arrival_display.setForeground(new java.awt.Color(219, 242, 255));
        vehicle_arrival_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicle_arrival_display.setText("123");
        jPanel2.add(vehicle_arrival_display);
        vehicle_arrival_display.setBounds(620, 450, 370, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Departure Date/Time");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(220, 550, 260, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":-");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(560, 550, 40, 40);

        vehicle_departure_display.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_departure_display.setForeground(new java.awt.Color(219, 242, 255));
        vehicle_departure_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicle_departure_display.setText("123");
        jPanel2.add(vehicle_departure_display);
        vehicle_departure_display.setBounds(620, 550, 370, 40);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Payment");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(220, 750, 260, 40);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":-");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(560, 750, 40, 40);

        vehicle_payment_display.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_payment_display.setForeground(new java.awt.Color(219, 242, 255));
        vehicle_payment_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicle_payment_display.setText("123");
        jPanel2.add(vehicle_payment_display);
        vehicle_payment_display.setBounds(620, 750, 370, 40);

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_rollover.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(880, 820, 190, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/document.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(790, 110, 70, 60);

        jLabel18.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(":-");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(560, 650, 40, 40);

        jLabel17.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Hours Parked");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(220, 650, 260, 40);

        vehicle_hours_parked.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_hours_parked.setForeground(new java.awt.Color(219, 242, 255));
        vehicle_hours_parked.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicle_hours_parked.setText("123");
        jPanel2.add(vehicle_hours_parked);
        vehicle_hours_parked.setBounds(620, 650, 370, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               Select_Individual_Record SIR = new Select_Individual_Record();
               SIR.setLocationRelativeTo(null);
               SIR.setSize(1100, 960);
               SIR.setResizable(false);
               SIR.setVisible(true);
               SIR.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   SIR.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Select_Individual_Record.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Individual_Record_View().setVisible(true);
               Individual_Record_View IRV = new Individual_Record_View();
               IRV.setLocationRelativeTo(null);
               IRV.setSize(1100, 960);
               IRV.setResizable(false);
               IRV.setVisible(true);
               IRV.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   IRV.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Individual_Record_View.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel vehicle_arrival_display;
    private javax.swing.JLabel vehicle_departure_display;
    private javax.swing.JLabel vehicle_hours_parked;
    private javax.swing.JLabel vehicle_payment_display;
    private javax.swing.JLabel vehicle_plate_display;
    private javax.swing.JLabel vehicle_type_display;
    // End of variables declaration//GEN-END:variables
}
