/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Function;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import dashboard.dashboard;
import java.awt.Font;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import org.joda.time.DateTime;
import org.joda.time.Period;

/**
 *
 * @author Vageesha
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Individual_Record_View
     */
    private Integer TPT = 0;
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        date_time_picker = new com.lavantech.gui.comp.DateTimePicker();
        date_time_picker.setFont(new Font("MV Boli", Font.PLAIN, 22));
        vehicle_type_display = new javax.swing.JLabel();
        arrival_date_time_display = new javax.swing.JLabel();
        payment_display = new javax.swing.JLabel();
        calculate_btn = new javax.swing.JButton();
        vehicle_plate_input = new javax.swing.JComboBox<>();
        AutoCompleteDecorator.decorate(vehicle_plate_input);
        vehicle_plate_input.addItem("");
        try {
            Connection conn = DatabaseConnection.connect();
            PreparedStatement DBOUTPUT = conn.prepareStatement("SELECT * FROM carDetails");
            ResultSet RS = DBOUTPUT.executeQuery();
            while(RS.next()){ 
                if(RS.getDate("departure_date_time") == null)
                vehicle_plate_input.addItem(RS.getString("vehicle_plate"));
            } 
            DBOUTPUT.close();
            RS.close();
            conn.close();
        }catch(Exception e) {
            System.out.println(e);
        }

        vehicle_plate_input.setSelectedIndex(0);

        vehicle_plate_input.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent event) {

                if (event.getStateChange() == ItemEvent.SELECTED) {
                    String txt = vehicle_plate_input.getSelectedItem().toString();
                    try {
                        Connection conn = DatabaseConnection.connect();
                        PreparedStatement DBOUTPUT2 = conn.prepareStatement("SELECT vehicle_type, arrival_date_time FROM carDetails WHERE vehicle_plate = ?");
                        DBOUTPUT2.setString(1, txt);
                        ResultSet RS2 = DBOUTPUT2.executeQuery();

                        if(RS2.next()){ 
                            vehicle_type_display.setText(RS2.getString("vehicle_type"));
                            Date date = RS2.getDate("arrival_date_time");
                            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd hh:mm a");  
                            String SAD = dateFormat.format(date);
                            arrival_date_time_display.setText(SAD);

                        }
                        DBOUTPUT2.close();
                        RS2.close();
                        conn.close();
                    }catch(Exception e) {
                        System.out.println(e);
                    }
                }
            }
        });
        save_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1100, 1100));

        jPanel2.setBackground(new java.awt.Color(51, 74, 95));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payment");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(450, 80, 200, 110);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Plate");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(100, 250, 260, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText(":-");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(370, 250, 40, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(":-");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(370, 360, 40, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vehicle Type");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 360, 260, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Arrival Date/Time");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(100, 470, 260, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":-");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(370, 470, 40, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Departure Date/Time");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(100, 580, 260, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":-");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(370, 580, 40, 40);

        jLabel15.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Payment");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(100, 840, 260, 40);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText(":-");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(370, 840, 40, 40);

        back_btn.setBackground(new java.awt.Color(51, 90, 255));
        back_btn.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        back_btn.setBorder(null);
        back_btn.setBorderPainted(false);
        back_btn.setContentAreaFilled(false);
        back_btn.setFocusPainted(false);
        back_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_rollover.png"))); // NOI18N
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel2.add(back_btn);
        back_btn.setBounds(880, 820, 190, 80);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment_icon.png"))); // NOI18N
        jPanel2.add(jLabel4);
        jLabel4.setBounds(660, 110, 70, 60);

        date_time_picker.setForeground(new java.awt.Color(0, 0, 116));
        date_time_picker.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        date_time_picker.setMinimumSize(new java.awt.Dimension(480, 40));
        date_time_picker.setPreferredSize(new java.awt.Dimension(480, 40));
        jPanel2.add(date_time_picker);
        date_time_picker.setBounds(460, 580, 480, 40);

        vehicle_type_display.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_type_display.setForeground(new java.awt.Color(255, 255, 255));
        vehicle_type_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(vehicle_type_display);
        vehicle_type_display.setBounds(460, 360, 480, 40);

        arrival_date_time_display.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        arrival_date_time_display.setForeground(new java.awt.Color(255, 255, 255));
        arrival_date_time_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(arrival_date_time_display);
        arrival_date_time_display.setBounds(460, 470, 480, 40);

        payment_display.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        payment_display.setForeground(new java.awt.Color(255, 255, 255));
        payment_display.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payment_display.setText("0.00");
        jPanel2.add(payment_display);
        payment_display.setBounds(460, 840, 200, 40);

        calculate_btn.setBackground(new java.awt.Color(51, 90, 255));
        calculate_btn.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        calculate_btn.setForeground(new java.awt.Color(255, 255, 255));
        calculate_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculate.png"))); // NOI18N
        calculate_btn.setBorder(null);
        calculate_btn.setBorderPainted(false);
        calculate_btn.setContentAreaFilled(false);
        calculate_btn.setFocusPainted(false);
        calculate_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/calculate_rollover.png"))); // NOI18N
        calculate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculate_btnActionPerformed(evt);
            }
        });
        jPanel2.add(calculate_btn);
        calculate_btn.setBounds(650, 660, 190, 80);

        vehicle_plate_input.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        vehicle_plate_input.setForeground(new java.awt.Color(0, 0, 116));
        jPanel2.add(vehicle_plate_input);
        vehicle_plate_input.setBounds(460, 250, 480, 40);

        save_btn.setBackground(new java.awt.Color(51, 90, 255));
        save_btn.setFont(new java.awt.Font("MV Boli", 0, 24)); // NOI18N
        save_btn.setForeground(new java.awt.Color(255, 255, 255));
        save_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        save_btn.setBorder(null);
        save_btn.setBorderPainted(false);
        save_btn.setContentAreaFilled(false);
        save_btn.setFocusPainted(false);
        save_btn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save_rollover.png"))); // NOI18N
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });
        jPanel2.add(save_btn);
        save_btn.setBounds(650, 820, 190, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        try {
                   d.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void calculate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculate_btnActionPerformed
        // TODO add your handling code here:
         String VP = vehicle_plate_input.getSelectedItem().toString();
         
         if(VP.equals("")){
             
               Popup pop = new Popup();
               pop.PopupOK_Init();
               pop.IncludeTxt("Please Select a Vehicle Plate");
               pop.setSize(515,301);
               pop.setLocationRelativeTo(null);
               pop.setResizable(false);
               pop.setVisible(true); 
               pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   pop.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Popup.class.getName()).log(Level.SEVERE, null, ex);
                }
         }else{
             
            GregorianCalendar GC = date_time_picker.getCalendar();
            String SD = arrival_date_time_display.getText();
            String VT = vehicle_type_display.getText();
            Double price = 0.0;
            Date date = GC.getTime();  
            Date dateA = null;
            
            try {
               Connection conn = DatabaseConnection.connect();
               PreparedStatement DBOUTPUT3 = conn.prepareStatement("SELECT price FROM carType_Price WHERE vehicle_type = ?");
               DBOUTPUT3.setString(1, VT);
               ResultSet RS3 = DBOUTPUT3.executeQuery();
               
               if(RS3.next()) 
                           price = RS3.getDouble("price");

               dateA = new SimpleDateFormat("yyyy-MM-dd hh:mm a").parse(SD);
             
                
               DBOUTPUT3.close();
               RS3.close();
               conn.close();
            } catch (Exception ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }

            DateTime startTime = new DateTime(dateA);
            DateTime endTime = new DateTime(date);

            Period p = new Period(startTime, endTime);
            long days = p.getDays();
            long hours = p.getHours();
            long minutes = p.getMinutes();
            
            double P = 0;
            if(days != 0){
                P = P + (price * 24 * days);
                TPT += (int) (24 * days); 
            }
            if(hours != 0){
                P = P + (price * hours);
                TPT += (int) hours;
            }
            if(minutes != 0){
                P = P + price;
                TPT += 1;
            }
         payment_display.setText(Double.toString(P));
         }
    }//GEN-LAST:event_calculate_btnActionPerformed

    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        // TODO add your handling code here:
        String PD = payment_display.getText();
        
        if(PD.equals("0.00")){
               Popup pop = new Popup();
               pop.PopupOK_Init();
               pop.IncludeTxt("Please Calculate the Payment");
               pop.setSize(515,301);
               pop.setLocationRelativeTo(null);
               pop.setResizable(false);
               pop.setVisible(true); 
               pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   pop.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Popup.class.getName()).log(Level.SEVERE, null, ex);
                }
        }else{
            String VP = vehicle_plate_input.getSelectedItem().toString();
            Double PP = Double.parseDouble(payment_display.getText());
            
            try {
                
                Connection conn = DatabaseConnection.connect();
                PreparedStatement DBOUTPUT4 = conn.prepareStatement("UPDATE carDetails SET departure_date_time = ?, hours_parked = ?, payment = ? WHERE vehicle_plate = ?");

                DBOUTPUT4.setString(4, VP);

                Date D1 = date_time_picker.getCalendar().getTime();
                java.sql.Date d1= new java.sql.Date(D1.getTime());
                DBOUTPUT4.setDate(1,d1);

                DBOUTPUT4.setInt(2,TPT);
                DBOUTPUT4.setDouble(3,PP);
                DBOUTPUT4.executeUpdate();
            
            DBOUTPUT4.close();
            conn.close();
            
        }catch(Exception e) {
            System.out.println(e);
        }
               Popup pop = new Popup();
               pop.PopupOK_Init();
               pop.IncludeTxt("Record Updated");
               pop.setGOT();
               pop.setSize(515,301);
               pop.setLocationRelativeTo(null);
               pop.setResizable(false);
               pop.setVisible(true); 
               pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   pop.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Popup.class.getName()).log(Level.SEVERE, null, ex);
                }
               
               this.dispose();
        }
    }//GEN-LAST:event_save_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Individual_Record_View().setVisible(true);
               Payment PAY = new Payment();
               PAY.setLocationRelativeTo(null);
               PAY.setSize(1100, 960);
               PAY.setResizable(false);
               PAY.setVisible(true);
               PAY.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   PAY.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arrival_date_time_display;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton calculate_btn;
    private com.lavantech.gui.comp.DateTimePicker date_time_picker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel payment_display;
    private javax.swing.JButton save_btn;
    private javax.swing.JComboBox<String> vehicle_plate_input;
    private javax.swing.JLabel vehicle_type_display;
    // End of variables declaration//GEN-END:variables
}
