/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_Function;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vageesha
 */
public class Select_Individual_Record extends javax.swing.JFrame {

    /**
     * Creates new form View_Divide
     */
    public Select_Individual_Record() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        JTableHeader header = jTable1.getTableHeader();
        header.setBackground(Color.WHITE);
        header.setForeground(Color.BLACK);
        header.setFont(new Font("MV Boli", Font.BOLD, 15));
        header.setPreferredSize(new Dimension(100, 40));
        jTable1.setRowHeight(30);
        searchtext = new javax.swing.JTextField();
        DocumentListener documentListener = new DocumentListener() {
            public void changedUpdate(DocumentEvent documentEvent) {

            }
            public void insertUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
            public void removeUpdate(DocumentEvent documentEvent) {

                TableRowSorter <TableModel> sorter = new TableRowSorter <TableModel>(((DefaultTableModel) jTable1.getModel())); 
                sorter.setRowFilter(RowFilter.regexFilter(searchtext.getText()));

                jTable1.setRowSorter(sorter);

            }
        };

        searchtext.getDocument().addDocumentListener(documentListener);
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 74, 95));
        jPanel1.setLayout(null);

        jButton4.setBackground(new java.awt.Color(204, 204, 204));
        jButton4.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/select_rollover.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(650, 820, 190, 80);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Select Individual Record");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 20, 520, 100);

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_rollover.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(880, 820, 190, 80);

        jTable1.setBackground(new java.awt.Color(219, 242, 255));
        jTable1.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 116));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CheckBox", "Vehicle Plate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        try {
            Connection conn = DatabaseConnection.connect();
            PreparedStatement DBOUTPUT5 = conn.prepareStatement("SELECT vehicle_plate FROM carDetails");
            ResultSet RS4 = DBOUTPUT5.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

            while(RS4.next())
            {

                model.addRow(new Object[]{false,RS4.getString("vehicle_plate")});
            }
            RS4.close();
            DBOUTPUT5.close();
            conn.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        JTableUtilities.setCellsAlignment(jTable1, SwingConstants.CENTER,1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 230, 1060, 560);

        searchtext.setBackground(new java.awt.Color(219, 242, 255));
        searchtext.setFont(new java.awt.Font("MV Boli", 0, 18)); // NOI18N
        searchtext.setForeground(new java.awt.Color(0, 0, 116));
        searchtext.setMaximumSize(new java.awt.Dimension(50, 36));
        searchtext.setPreferredSize(new java.awt.Dimension(50, 36));
        jPanel1.add(searchtext);
        searchtext.setBounds(120, 140, 280, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Search");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 140, 80, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 960, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int row = jTable1.getRowCount();
        int h=0;
        int count = 0;
        boolean check;
        String VP = null; 
        
         while (h < row){
         check= (Boolean) jTable1.getValueAt(h,0); 
         
         if (check == true){
            VP = jTable1.getValueAt(h,1).toString();
            count++;
         }
         
         h++;
         }
         
        switch (count) {
            case 1:
                Individual_Record_View IRV = new Individual_Record_View();
                IRV.setLocationRelativeTo(null);
                IRV.setSize(1100, 960);
                IRV.getDetails(VP);
                IRV.setResizable(false);
                IRV.setVisible(true);
                IRV.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                try {
                    IRV.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Individual_Record_View.class.getName()).log(Level.SEVERE, null, ex);
                }
                this.dispose();
                break;
            case 0:
                {
                    Popup pop = new Popup();
                    pop.PopupOK_Init();
                    pop.IncludeTxt("Please Select a Record");
                    pop.setSize(515,301);
                    pop.setLocationRelativeTo(null);
                    pop.setResizable(false);
                    pop.setVisible(true);
                    pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    try {
                        pop.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                    } catch (IOException ex) {
                        Logger.getLogger(Popup.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                }
            default:
                {
                    Popup pop = new Popup();
                    pop.PopupOK_Init();
                    pop.IncludeTxt("Please Select a only one Record");
                    pop.setSize(515,301);
                    pop.setLocationRelativeTo(null);
                    pop.setResizable(false);
                    pop.setVisible(true);
                    pop.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                    try {
                        pop.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                    } catch (IOException ex) {
                        Logger.getLogger(Popup.class.getName()).log(Level.SEVERE, null, ex);
                    }   break;
                }
        }
         
         
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
               View_Divide VD = new View_Divide();
               VD.setLocationRelativeTo(null);
               VD.setSize(1100, 960);
               VD.setResizable(false);
               VD.setVisible(true);
               VD.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   VD.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(View_Divide.class.getName()).log(Level.SEVERE, null, ex);
                }
               this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
            // Set cross-platform Java L&F (also called "Metal")
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } 
    catch (UnsupportedLookAndFeelException e) {
       // handle exception
    }
    catch (ClassNotFoundException e) {
       // handle exception
    }
    catch (InstantiationException e) {
       // handle exception
    }
    catch (IllegalAccessException e) {
       // handle exception
    }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               Select_Individual_Record SIR = new Select_Individual_Record();
               SIR.setLocationRelativeTo(null);
               SIR.setSize(1100, 960);
               SIR.setResizable(false);
               SIR.setVisible(true);
               SIR.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
               try {
                   SIR.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(Select_Individual_Record.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchtext;
    // End of variables declaration//GEN-END:variables
}
