/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportnSearch;

import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import dashboard.dashboard;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author imani
 */
public class main_report extends javax.swing.JFrame {

    /**
     * Creates new form main_report
     */
    public main_report() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btn_dailyReport = new javax.swing.JButton();
        btn_monthlyReport = new javax.swing.JButton();
        btn_catReport = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        lbl_monthlytopic1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(191, 193, 190));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 74, 95));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/graph-3068300__340.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 620, 310));

        jPanel3.setBackground(new java.awt.Color(51, 74, 95));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_dailyReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_dailyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_daily-report.png"))); // NOI18N
        btn_dailyReport.setBorder(null);
        btn_dailyReport.setBorderPainted(false);
        btn_dailyReport.setContentAreaFilled(false);
        btn_dailyReport.setFocusPainted(false);
        btn_dailyReport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_daily-report (1).png"))); // NOI18N
        btn_dailyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dailyReportActionPerformed(evt);
            }
        });
        jPanel3.add(btn_dailyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 63));

        btn_monthlyReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_monthlyReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_monthly-report (1).png"))); // NOI18N
        btn_monthlyReport.setBorder(null);
        btn_monthlyReport.setBorderPainted(false);
        btn_monthlyReport.setContentAreaFilled(false);
        btn_monthlyReport.setFocusPainted(false);
        btn_monthlyReport.setMaximumSize(new java.awt.Dimension(167, 25));
        btn_monthlyReport.setMinimumSize(new java.awt.Dimension(167, 25));
        btn_monthlyReport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_monthly-report.png"))); // NOI18N
        btn_monthlyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_monthlyReportActionPerformed(evt);
            }
        });
        jPanel3.add(btn_monthlyReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, 63));

        btn_catReport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_catReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_customized-report.png"))); // NOI18N
        btn_catReport.setBorder(null);
        btn_catReport.setBorderPainted(false);
        btn_catReport.setContentAreaFilled(false);
        btn_catReport.setFocusPainted(false);
        btn_catReport.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_customized-report (1).png"))); // NOI18N
        btn_catReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_catReportActionPerformed(evt);
            }
        });
        jPanel3.add(btn_catReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 63));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setContentAreaFilled(false);
        backbtn.setFocusPainted(false);
        backbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back (1).png"))); // NOI18N
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel3.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 430, 200));

        lbl_monthlytopic1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lbl_monthlytopic1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_monthlytopic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_monthlytopic1.setText("Reports");
        jPanel2.add(lbl_monthlytopic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 280, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 1100, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_catReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_catReportActionPerformed
        // TODO add your handling code here:
        categorized_report cr = new categorized_report();
        cr.setVisible(true);
        this.setVisible(false);
        try {
                   cr.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(categorized_report.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btn_catReportActionPerformed

    private void btn_monthlyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_monthlyReportActionPerformed
        // TODO add your handling code here:
        monthly_report mr = new monthly_report();
        mr.setVisible(true);
        this.setVisible(false);
        try {
                   mr.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(monthly_report.class.getName()).log(Level.SEVERE, null, ex);
                }
    }//GEN-LAST:event_btn_monthlyReportActionPerformed

    private void btn_dailyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dailyReportActionPerformed
        // TODO add your handling code here:
        daily_report rp = new daily_report();
        rp.setVisible(true);
        this.setVisible(false);
        try {
                   rp.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(daily_report.class.getName()).log(Level.SEVERE, null, ex);
                }
      
     
    }//GEN-LAST:event_btn_dailyReportActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        try {
                   d.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main_report mn = new main_report();
                mn.setSize(1100, 960);
                        mn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btn_catReport;
    private javax.swing.JButton btn_dailyReport;
    private javax.swing.JButton btn_monthlyReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_monthlytopic1;
    // End of variables declaration//GEN-END:variables
}
