/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reportnSearch;
import static com.sun.org.apache.bcel.internal.util.SecuritySupport.getResourceAsStream;
import dashboard.dashboard;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException; 
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import reportnSearch.dbConnection;
/**
 *
 * @author imani
 */
public class vehicle_search extends javax.swing.JFrame {

    /**
     * Creates new form vehicle_search
     */
    Connection con = null;
    ResultSet rs = null;
    
    public vehicle_search() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
    }
    
   
    
    public void actionPerformed(){
        try{
           
            //connect to database
            con = dbConnection.connect();
            Statement stmt = con.createStatement();
            String vehicleNumber = txt_search.getText();
            String query = "SELECT vehicle_plate,vehicle_type FROM carDetails WHERE vehicle_plate = '" + vehicleNumber + "'";
            rs = stmt.executeQuery(query);
            
            if(rs.next()){
                String vehicleNo = rs.getString(1);
                String vehicleType = rs.getString(2);
                
                if(Integer.parseInt(vehicleType) == 1){
                    lbl_vehT.setText("Car");
                }
                else if(Integer.parseInt(vehicleType) == 2){
                    lbl_vehT.setText("Van");
                }
                else if(Integer.parseInt(vehicleType) == 3){
                    lbl_vehT.setText("Motor Bike");
                }
                else if(Integer.parseInt(vehicleType) == 4){
                    lbl_vehT.setText("Three Wheeler");
                }
                else{
                    System.out.println("Vehicle not found");
                }
                
                lbl_vehNumber.setText(vehicleNo);
                //lbl_vehT.setText(vehicleType);
                
                JOptionPane.showMessageDialog(null, "Vehicle found");
            }
            else{
                JOptionPane.showMessageDialog(null, "Vehicle not found");
            } 
            //st.close();
            //con.close();
        }catch(SQLException ex){
            System.out.println(ex.getMessage());
            //JOptionPane.showMessageDialog(null,"Could not search" );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        backbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_vehNo = new javax.swing.JLabel();
        lbl_vehType = new javax.swing.JLabel();
        lbl_vehNumber = new javax.swing.JLabel();
        lbl_vehT = new javax.swing.JLabel();
        lbl_monthlytopic1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 74, 95));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, -1));

        jPanel3.setBackground(new java.awt.Color(51, 74, 95));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_search.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        jPanel3.add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 480, 35));

        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back.png"))); // NOI18N
        backbtn.setBorder(null);
        backbtn.setBorderPainted(false);
        backbtn.setContentAreaFilled(false);
        backbtn.setFocusPainted(false);
        backbtn.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/button_back (1).png"))); // NOI18N
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        jPanel3.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 74, 95));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_vehNo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_vehNo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehNo.setText("Vehicle Number");
        jPanel2.add(lbl_vehNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 250, 40));

        lbl_vehType.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_vehType.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehType.setText("Vehicle Type");
        jPanel2.add(lbl_vehType, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 250, 41));

        lbl_vehNumber.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_vehNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehNumber.setText("0");
        jPanel2.add(lbl_vehNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 200, 40));

        lbl_vehT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_vehT.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehT.setText("0");
        jPanel2.add(lbl_vehT, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 200, 41));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 960, 90));

        lbl_monthlytopic1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        lbl_monthlytopic1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_monthlytopic1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_monthlytopic1.setText("Search");
        jPanel3.add(lbl_monthlytopic1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 280, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Vehicle Details");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 340, -1));

        btn_search.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_search.png"))); // NOI18N
        btn_search.setBorder(null);
        btn_search.setBorderPainted(false);
        btn_search.setContentAreaFilled(false);
        btn_search.setFocusPainted(false);
        btn_search.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/reportnResearch_Icons/button_search (1).png"))); // NOI18N
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel3.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 40, -1, 63));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        dashboard d = new dashboard();
        d.setVisible(true);
        try {
                   d.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
        dispose();
    }//GEN-LAST:event_backbtnActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        // TODO add your handling code here:
        actionPerformed();
    }//GEN-LAST:event_btn_searchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicle_search.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vehicle_search v = new vehicle_search();
                v.setVisible(true);
                v.setSize(1100, 390);
                 try {
                   v.setIconImage(ImageIO.read(getResourceAsStream("Images/frameIcon.png")));
                } catch (IOException ex) {
                    Logger.getLogger(vehicle_search.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_monthlytopic1;
    private javax.swing.JLabel lbl_vehNo;
    private javax.swing.JLabel lbl_vehNumber;
    private javax.swing.JLabel lbl_vehT;
    private javax.swing.JLabel lbl_vehType;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables
}
